name: Test MoviePy

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MoviePy + FFmpeg
        run: |
          pip install --no-cache-dir moviepy
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run main.py
        run: python main.py
